[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
# Black is very opinionated, so we're keeping it simple

[tool.isort]
profile = "black"
line_length = 120
skip = [".git", "__pycache__", ".tox", ".eggs", "*.egg", "build", "dist"]

[tool.mypy]
python_version = "3.8"
warn_return_any = false
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
follow_imports = "skip"
ignore_missing_imports = true

[tool.ruff]
line-length = 120
target-version = "py38"
select = ["E", "F"]
ignore = ["E203", "E501", "E402", "F401", "F403", "F405"]
exclude = [
    ".git",
    "__pycache__",
    ".tox",
    ".eggs",
    "*.egg",
    "build",
    "dist",
    "venv",
    ".venv",
]
