name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort mypy ruff

    - name: Check formatting with black
      run: |
        black --check --diff . || echo "Black formatting issues found (not failing build)"

    - name: Check imports with isort
      run: |
        isort --check --diff . || echo "Import sorting issues found (not failing build)"

    - name: Check with ruff
      run: |
        ruff check . --exit-zero

    - name: Type check with mypy
      run: |
        mypy --ignore-missing-imports --follow-imports=skip --disallow-untyped-defs=False src/ || echo "Type checking issues found (not failing build)"
